= devcon

Devcon is a container that includes useful scripts, tools and languages. Container is based on https://rockylinux.org/[Rocky Linux] and it uses systemd.

== Use cases

* Need to have Linux-environment in Windows or Mac.
* Need to have various tools without installing them to host machine.
* Need to have development environments across multiple hosts.
** For example, you have Windows and Mac and you work on both.
** Using this container enables to have same environment in both hosts.
** Files you work on, like source code, is in Dropbox or similar and synced between hosts.

== Usage



* Start container:
```
docker run -it --rm --name devcon --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 3443:3000 -p 2222:22 devcon
```
* Add root password and persistent volumes:
```
docker run -it --rm --name devcon --privileged -p 2222:22 -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 3443:3000 -e ROOT_PASSWORD=passw0rd -v C:\HOME\work:/root/host/work -v d:\downloads:/root/downloads devcon  
```
* Install what is needed and then create new image using:
```
docker commit <container> repo:tag
```

== Scripts

See _setup-scripts_-directory for available install scripts.

== Environment variables

.Environment variables that can be used when starting the container.
|===
|Name|Value|Default|Description

|ROOT_PASSWORD
|any string
|Random password
|Set root password. Password is written to `/root/startup-info.txt` file

|DEVCON_USER_PASSWORD
|any string
|Random password
|Set devcon-user password. Password is written to `/root/startup-info.txt` file

|DISPLAY
|<X display>
|host.docker.internal:0
|Set display for X (default value is for Windows hosts).


|===
