apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devcon-privileged-role
  namespace: devcon
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - devcon-privileged-scc
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
