#!/bin/bash

#env variables
#check latest python: https://www.python.org
PYTHON_VERSION=3.12.3

#IBM Cloud CLI https://cloud.ibm.com/docs/cli
#https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/
IBMCLOUD_VERSION=2.24.0

#https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
OPENSHIFT_CLIENT_VERSION=4.14.20

#check available by listing what are possible to install
#dnf install java-*devel
#JAVA_VERSION=java-1.8.0
#JAVA_VERSION=java-11
#JAVA_VERSION=java-17
JAVA_VERSION=java-21

#check latest Maven version https://maven.apache.org/download.cgi
MAVEN_VERSION=3.9.6

#IBM Cloud Pak plugin
#https://github.com/IBM/ibm-pak
IBMCLOUDPAKPLUGIN_VERSION=1.14.1

#Ruby
#check latest version: https://www.ruby-lang.org/en/downloads/
RUBY_VERSION=3.3.1

#PostgreSQL, https://www.postgresql.org/
POSTEGRESQL_VERSION=16

#ImageMagic version, https://github.com/ImageMagick/ImageMagick/releases
IMAGEMAGICK_VERSION=7.1.1-31
 
#major MongoDB version (6, 7, etc.)
MONGODB_VERSION=6

#source all functions
for f in /setup/tool/*sh; do source $f; done

cd $cdir

function help
{
    echo "DevCon Tool."
    echo ""
    echo "Usage: $0 <cmd> [<cmd-options>]"
    echo ""
    echo "Commands:"
    echo ""
    echo "  help                      - This help."
    echo "  install-argocd            - Install latest Argo CD CLI."
    echo "  install-asciidoctor       - Install latest asciidoctor (requires Ruby)."
    echo "  install-clang             - Install gcc, clang and make."
    echo "  install-entertainment     - Install various entertaining software."
    echo "  install-ffmpeg            - Install ffmpeg tool."
    echo "  install-ibmcloud-cli      - Install IBM Cloud CLI (${IBMCLOUD_VERSION}) client with all plugins."
    echo "  install-ibmpakplugin      - Install IBM Cloud Pak oc-plugin (${IBMCLOUDPAKPLUGIN_VERSION}) and deprecated cloudctl CLI."
    echo "  install-imagemagick       - Install imagemagick (${IMAGEMAGICK_VERSION}) from source."
    echo "  install-java              - Install Java (${JAVA_VERSION}) from dnf repository."
    echo "  install-jupyter           - Install JupyterLab."
    echo "  start-jupyter             - Start JupyterLab, listening on port 8888."
    echo "  install-kubeterminal      - Install KubeTerminal."
    echo "  install-maven             - Install Maven (${MAVEN_VERSION})."
    echo "  install-mongosh           - Install mongosh-client."    
    echo "  install-openshift-client  - Install OpenShift (${OPENSHIFT_CLIENT_VERSION}) clients (oc, openshift-install, etc.)."
    echo "  install-postgresql-client - Install Postgresql client (${POSTEGRESQL_VERSION})."
    echo "  install-python            - Install Python (${PYTHON_VERSION}) from source."
    echo "  install-ruby              - Install Ruby (${RUBY_VERSION}) from source."
    echo ""
    exit 1
}

function error
{
    echo "ERROR: $1"
    exit 1
}

if [[ "$1" == "" ]]; then
    #echo "No commands."
    help
fi

#call function as sudo
#https://unix.stackexchange.com/a/438712
function Sudo {
    local firstArg=$1
    if [ $(type -t $firstArg) = function ]
    then
        shift && command sudo bash -c "$(declare -f $firstArg);$firstArg $*"
    elif [ $(type -t $firstArg) = alias ]
    then
        alias sudo='\sudo '
        eval "sudo $@"
    else
        command sudo "$@"
    fi
}

#call functions
#note 'shift' command moves ARGS to the left 

case "$1" in
    install-ffmpeg)
        sudo dnf -y install ffmpeg*
    ;;
    install-imagemagick)
        install-imagemagick $IMAGEMAGICK_VERSION
    ;;    
    install-jupyter)
        pip install jupyterlab
    ;;
    start-jupyter)
        export JUPYTER_PORT=8888
        jupyter lab --ip=0.0.0.0
    ;;
    install-ibmcloud-cli)
        install-ibmcloud-cli $IBMCLOUD_VERSION
    ;;
    install-ibmpakplugin)
        install-cloudpakplugin $IBMCLOUDPAKPLUGIN_VERSION
    ;;
    install-openshift-client)
        downloadOpenShiftClient openshift-client-linux.tar.gz
        downloadOpenShiftClient openshift-install-linux.tar.gz
        downloadOpenShiftClient opm-linux.tar.gz
        downloadOpenShiftClient oc-mirror.tar.gz
        downloadOpenShiftClient ccoctl-linux.tar.gz
    ;;
    install-java)
        #install OpenJDK from repository
        install-java $JAVA_VERSION
    ;;
    install-maven)
        #install Maven
        install-maven $MAVEN_VERSION
        export PATH=$PATH:/usr/local/bin/apache-maven-$MAVEN_VERSION/bin
        #setup maven, download recent artifacts based on dummy project
        setup-maven
        echo ""
        echo "Open a new shell or sdet PATH in the current shell:"
        echo "export PATH=\$PATH:/usr/local/bin/apache-maven-$MAVEN_VERSION/bin"

    ;;
    install-python)
        #install python from source
        install-python $PYTHON_VERSION
    ;;
    install-entertainment)
        install-rain
        install-cmatrix
        install-2048

        echo ""
        echo "Entertaining commands:"
        echo "  2048"
        echo "  cmatrix"
        echo "  rain"

    ;;
    install-kubeterminal)
        install-kubeterminal
    ;;
    install-argocd)
        install-argocd
    ;;
    install-ruby)
        install-ruby $RUBY_VERSION
    ;;
    install-asciidoctor)
        install-asciidoctor
    ;;
    install-mongosh)
        install-mongosh
    ;;
    install-postgresql-client)
        install-postgresql-client $POSTEGRESQL_VERSION
    ;;
    install-clang)
        sudo dnf -y install gcc clang make
    ;;
    help)
        help
    ;;
    *)
        help
    ;;
esac

