#!/bin/bash

#env variables
#check latest python: https://www.python.org
PYTHON_VERSION=3.11.4

#IBM Cloud CLI https://cloud.ibm.com/docs/cli
#https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/
IBMCLOUD_VERSION=2.19.1

#https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
OPENSHIFT_CLIENT_VERSION=4.12.27

#check available by listing what are possible to install
#dnf install java-*devel
#JAVA_VERSION=java-1.8.0
#JAVA_VERSION=java-11
JAVA_VERSION=java-17

#check latest Maven version https://maven.apache.org/download.cgi
MAVEN_VERSION=3.9.4

#IBM Cloud Pak plugin
#https://github.com/IBM/ibm-pak
IBMCLOUDPAKPLUGIN_VERSION=1.9.0

#Ruby
#check latest version: https://www.ruby-lang.org/en/downloads/
RUBY_VERSION=3.2.2

#source all functions
for f in /setup/tool/*sh; do source $f; done

cd $cdir

function help
{
    echo "DevCon Tool."
    echo ""
    echo "Usage: $0 <cmd> [<cmd-options>]"
    echo ""
    echo "Commands:"
    echo ""
    echo "  help                     - This help."
    echo "  argocd-install           - Install latest Argo CD CLI."
    echo "  asciidoctor-install      - Install latest asciidoctor (requires Ruby)."
    echo "  entertainment-install    - Install various entertaining software."
    echo "  ffmpeg-install           - Install ffmpeg tool."
    echo "  ibmcloud-install         - Install IBM Cloud CLI (${IBMCLOUD_VERSION}) client with all plugins."
    echo "  ibmpakplugin-install     - Install IBM Cloud Pak oc-plugin (${IBMCLOUDPAKPLUGIN_VERSION}) and deprecated cloudctl CLI."
    echo "  imagemagick-install      - Install imagemagick tool."
    echo "  java-install             - Install Java (${JAVA_VERSION}) from dnf repository."
    echo "  jupyter-install          - Install JupyterLab."
    echo "  jupyter-start            - Start JupyterLab, listening on port 8888."
    echo "  kubeterminal-install     - Install KubeTerminal."
    echo "  maven-install            - Install Maven (${MAVEN_VERSION})."
    echo "  mongosh-install          - Install mongosh-client."    
    echo "  openshift-client-install - Install OpenShift (${OPENSHIFT_CLIENT_VERSION}) clients (oc, openshift-install, etc.)."
    echo "  python-install           - Install Python (${PYTHON_VERSION}) from source."
    echo "  ruby-install             - Install Ruby (${RUBY_VERSION}) from source."
    echo ""
    exit 1
}

function error
{
    echo "ERROR: $1"
    exit 1
}

if [[ "$1" == "" ]]; then
    #echo "No commands."
    help
fi

#call function as sudo
#https://unix.stackexchange.com/a/438712
function Sudo {
    local firstArg=$1
    if [ $(type -t $firstArg) = function ]
    then
        shift && command sudo bash -c "$(declare -f $firstArg);$firstArg $*"
    elif [ $(type -t $firstArg) = alias ]
    then
        alias sudo='\sudo '
        eval "sudo $@"
    else
        command sudo "$@"
    fi
}

#call functions
#note 'shift' command moves ARGS to the left 

case "$1" in
    ffmpeg-install)
        sudo dnf -y install ffmpeg*
    ;;
    imagemagick-install)
        sudo dnf -y install ImageMagick ImageMagick-devel
    ;;    
    jupyter-install)
        pip install jupyterlab
    ;;
    jupyter-start)
        export JUPYTER_PORT=8888
        jupyter lab --ip=0.0.0.0
    ;;
    ibmcloud-install)
        install-ibmcloud-cli $IBMCLOUD_VERSION
    ;;
    ibmpakplugin-install)
        install-cloudpakplugin $IBMCLOUDPAKPLUGIN_VERSION
    ;;
    openshift-client-install)
        downloadOpenShiftClient openshift-client-linux.tar.gz
        downloadOpenShiftClient openshift-install-linux.tar.gz
        downloadOpenShiftClient opm-linux.tar.gz
        downloadOpenShiftClient oc-mirror.tar.gz
        downloadOpenShiftClient ccoctl-linux.tar.gz
    ;;
    java-install)
        #install OpenJDK from repository
        install-java $JAVA_VERSION
    ;;
    maven-install)
        #install Maven
        install-maven $MAVEN_VERSION
        export PATH=$PATH:/usr/local/bin/apache-maven-$MAVEN_VERSION/bin
        #setup maven, download recent artifacts based on dummy project
        setup-maven
        echo ""
        echo "Open a new shell or sdet PATH in the current shell:"
        echo "export PATH=\$PATH:/usr/local/bin/apache-maven-$MAVEN_VERSION/bin"

    ;;
    python-install)
        #install python from source
        install-python $PYTHON_VERSION
    ;;
    entertainment-install)
        install-rain
        install-cmatrix
        install-2048

        echo ""
        echo "Entertaining commands:"
        echo "  2048"
        echo "  cmatrix"
        echo "  rain"

    ;;
    kubeterminal-install)
        install-kubeterminal
    ;;
    argocd-install)
        install-argocd
    ;;
    ruby-install)
        install-ruby $RUBY_VERSION
    ;;
    asciidoctor-install)
        install-asciidoctor
    ;;
    mongosh-install)
        install-mongosh
    ;;
    help)
        help
    ;;
    *)
        help
    ;;
esac

