#!/bin/bash

#devcon tool script for installation etc.

#source all functions
for f in /setup/tool/*sh; do source $f; done

cd $cdir

function help
{
    echo "DevCon Tool."
    echo ""
    echo "Usage: $0 <cmd> [<cmd-options>]"
    echo ""
    echo "Commands:"
    echo ""
    echo "  help                     - This help."
    echo "  ffmpeg-install           - Install ffmpeg tool."
    echo "  ibmcloud-install         - Install IBM Cloud CLI client with all plugins."
    echo "  imagemagick-install      - Install imagemagick tool."
    echo "  java-install             - Install Java from dnf repository."
    echo "  jupyter-install          - Install JupyterLab."
    echo "  jupyter-start            - Start JupyterLab, listening on port 8888."
    echo "  openshift-client-install - Install OpenShift clients (oc, openshift-install, etc.)."
    echo ""
    exit 1
}

function error
{
    echo "ERROR: $1"
    exit 1
}

if [[ "$1" == "" ]]; then
    #echo "No commands."
    help
fi

#call function as sudo
#https://unix.stackexchange.com/a/438712
function Sudo {
    local firstArg=$1
    if [ $(type -t $firstArg) = function ]
    then
        shift && command sudo bash -c "$(declare -f $firstArg);$firstArg $*"
    elif [ $(type -t $firstArg) = alias ]
    then
        alias sudo='\sudo '
        eval "sudo $@"
    else
        command sudo "$@"
    fi
}

#call functions
#note 'shift' command moves ARGS to the left 

case "$1" in
    ffmpeg-install)
        sudo dnf -y install ffmpeg*
    ;;
    imagemagick-install)
        sudo dnf -y install ImageMagick ImageMagick-devel
    ;;    
    jupyter-install)
        pip install jupyterlab
    ;;
    jupyter-start)
        export JUPYTER_PORT=8888
        jupyter lab --ip=0.0.0.0
    ;;
    ibmcloud-install)
        #IBM Cloud CLI https://cloud.ibm.com/docs/cli
        #check latest release
        #https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/
        IBMCLOUD_VERSION=2.18.0
        install-ibmcloud-cli $IBMCLOUD_VERSION
    ;;
    openshift-client-install)
        #check latest versions
        #https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
        OPENSHIFT_CLIENT_VERSION=4.12.27

        downloadOpenShiftClient openshift-client-linux.tar.gz
        downloadOpenShiftClient openshift-install-linux.tar.gz
        downloadOpenShiftClient opm-linux.tar.gz
        downloadOpenShiftClient oc-mirror.tar.gz
        downloadOpenShiftClient ccoctl-linux.tar.gz
    ;;
    java-install)
        #install OpenJDK from repository
        #check available by listing what are possible to install
        #dnf install java-*devel

        #JAVA_VERSION=java-1.8.0
        #JAVA_VERSION=java-11
        JAVA_VERSION=java-17
        install-java $JAVA_VERSION
    ;;
    help)
        help
    ;;
    *)
        help
    ;;
esac

