apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devcon-rolebinding
  namespace: devcon
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devcon-privileged-role
subjects:
- kind: ServiceAccount
  name: devcon-sa
  namespace: devcon
