#build and push base container

name: Clients container build and push

on:
  workflow_dispatch:
jobs:
  call-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      tagname: clients
      dockerfile: clients.dockerfile
    secrets: inherit
