#workflow to build and push container
#called by other workflows
name: Container build and push

on:
  workflow_call:
    inputs:
      tagname:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Docker Build, Tag & Push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kazhar/devcon
        registry: docker.io
        tags: ${{ inputs.tagname }}
        dockerfile: ${{ inputs.dockerfile }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}