name: IBM and OpenShift clients container build and push

on:
  workflow_dispatch:

jobs:
  call-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      tagname: ocp
      dockerfile: containers/ibm-ocp-clients.containerfile
    secrets: inherit
      
        