name: Java container build and push

on:
  workflow_dispatch:

jobs:
  call-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      tagname: java
      dockerfile: containers/java.containerfile
    secrets: inherit
      
        